apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: todolist-keyvault
  labels: 
    azure.azureauthority.in: todo-list-app
    app: todo-list
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 9914e0e3-b555-4c08-91c6-cc701a5565dc
    keyvaultName: kvproject378924
    objects:  |
      array:
        - |
          objectName: config
          objectType: secret
          objectAlias: config.json
    tenantId: 784023b3-ac7b-4ae4-aa50-2b5b86ee9dfa